# Generated by Django 3.1.2 on 2020-10-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201007_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='investor',
            name='community_contributions',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='bin',
            name='gives_rewards',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='deposits_made',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='gives_rewards',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='person',
            name='community_contributions',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='person',
            name='deposits_made',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='person',
            name='rewards',
            field=models.IntegerField(default='0'),
        ),
    ]
